coverage>=7.2.7,<7.11
tornado>=6.2,<6.6
# 2.5 seems to break test_proxy_rejection by hanging forever
python-socks==2.4.4
pytest>=7.4.4,<9
pytest-timeout>=2.3.1,<3
trustme>=0.9.0,<2
cryptography<40.0.0; python_version <= '3.8'
cryptography<47; python_version > '3.8'
backports.zoneinfo==0.2.1; python_version<"3.9"
tzdata==2024.2; python_version<"3.8"
towncrier==21.9.0
pytest-asyncio>=0.21.1,<=1.2.0
aiofile>=2,<4
pytest-xdist>=3,<4
pytest-cov>=4,<8
